name: Cargo Builder for Pi 5 ARM Release-With-Tag

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build for Raspberry Pi 5 (64-bit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Install Cross
        run: curl -L https://github.com/cross-rs/cross/releases/latest/download/cross-x86_64-unknown-linux-musl.tar.gz | tar xz -C /usr/local/bin

      - name: Install JACK dependencies
        run: sudo apt-get install -y libjack-jackd2-dev pkg-config

      - name: Build
        run: cross build --release --target aarch64-unknown-linux-gnu

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pi-5-binary
          path: |
            target/aarch64-unknown-linux-gnu/release/*
            !target/aarch64-unknown-linux-gnu/release/deps
            !target/aarch64-unknown-linux-gnu/release/build
            !target/aarch64-unknown-linux-gnu/release/*.d
